### PR TITLE
[feat] CASIO Calc

### PR DESCRIPTION
**Pull request by iuu6**
Add `fx-ES series`, `fx-ES PLUS series`, `ClassWiz series` and most of `fx-ES PLUS (2nd Edition)` series calculators.
Added information about tags and contributors from CASIO

Thanks for MKStoler <MKStoler1024@proton.me>

### CODE REVIEW

**Comment by MKStoler4096** [comment]
i think it's not a good idea to publish this software to this repo? 
maybe it's a good idea to pubilsh this software into a new repo?
This is an introductory repo, though

**Comment by Aris-Offline** [comment]
You commit the code directly to the repo?

**Comment by MKStoler4096** [comment]
> You commit the code directly to the repo?

maybe not(?)
seems just the release software not the code

**Comment by iuu6** [comment]
> > You commit the code directly to the repo?
> 
> maybe not(?) seems just the release software not the code

CASIO itself is closed source software, how did he get the code?

**Comment by iuu6** [comment]
> i think it's not a good idea to publish this software to this repo? maybe it's a good idea to pubilsh this software into a new repo? This is an introductory repo, though

There is no code here, just the built exe file.
The detailed compilation steps are described in the README in the CASIO directory.

**Comment by iuu6** [comment]
> why not link to your repo which has the release software?

Since it's closed source software, I'm not releasing it in the repository.

> Due to copyright issues, I do not allow you to directly upload binary distribution packages with commercial copyrights to this repository. You can only submit external links to the software, but cannot directly host the binary distribution packages in this repository!

Hmm…I think uploading it to Google Drive to share might be a good option?

**Comment by Aris-Offline** [comment]
> > i think it's not a good idea to publish this software to this repo? maybe it's a good idea to pubilsh this software into a new repo? This is an introductory repo, though
> 
> There is no code here, just the built exe file. The detailed compilation steps are described in the README in the CASIO directory.

it only provides information, not program.

**Pull request closed without merging**
